# Panamax configuration example: the application

FROM zanco/apache-php5

MAINTAINER docker@zanconsulting.com

RUN rm /var/www/html/index.html

ADD index.php /var/www/html/index.php
ADD config.php /var/www/html/config.php

